#   docker-compose build
#   docker-compose up

version: "3.7"

services:
  web:
    container_name: "argebackend"
    image: "argebackend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./argebackend:/var/www/argebackend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
  client:
    build: frontend
    ports:
      - 4000:80
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourSTRONG!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - app-network
  nginx:
    build: nginx
    ports:
      - 80:80
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  local_postgres_data: {}
