#   docker-compose build
#   docker-compose up

version: "3.7"

services:
  web:
    container_name: "argebackend"
    image: "argebackend"
    build:
      context: ./argebackend
      dockerfile: Dockerfile
    volumes:
      - ./argebackend:/var/www/argebackend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
    networks:
      - app-network
  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
    networks:
      - app-network
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
  nginx:
    container_name: argefrontend
    image: argefrontend
    build:
      context: ./argefrontend
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"

    networks:
      - app-network
  omnidb:
    container_name: omnidb
    image: omnidb
    privileged: true
    user: root
    build:
      context: ./omnidb
      dockerfile: Dockerfile
    volumes:
      - $PWD/omnidb_data:/etc/omnidb:Z
    ports:
      - "25482:25482"
      - "8080:8080"

    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  local_postgres_data: {}
