server {
     
    listen 0.0.0.0:80;
    listen [::]:80;
    listen       443 ssl;
    server_name  10.55.25.197;
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    default_type application/octet-stream;

    gzip                    on;
    gzip_comp_level         6;
    gzip_vary               on;
    gzip_min_length         1000;
    gzip_proxied            any;
    gzip_types              text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers            16 8k;
    client_max_body_size    256M;

 
 

      location / {

        root   /usr/share/nginx/html;
        index  index.html index.htm;
              try_files $uri $uri/ /index.html =404;
    }

}