// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using argebackend;

namespace argebackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210204081042_kontrol")]
    partial class kontrol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("argebackend.Models.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("argebackend.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Tc")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("argebackend.Models.Basvuru", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BasvuruForm")
                        .HasColumnType("text");

                    b.Property<long>("BasvuruNo")
                        .HasColumnType("bigint");

                    b.Property<string>("BasvuruTuru")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Durum")
                        .HasColumnType("text");

                    b.Property<int>("DurumId")
                        .HasColumnType("integer");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Basvurus");
                });

            modelBuilder.Entity("argebackend.Models.BsvNo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BasvuruNo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BsvNos");
                });

            modelBuilder.Entity("argebackend.Models.Kontrol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("anketSorulariUygunmu")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaAmac")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaBaslik")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaBilimselYararAciklanmismi")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaEvreni")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaHipotez")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaStatu")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaTuru")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaYeri")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaYontem")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaZamanAralik")
                        .HasColumnType("text");

                    b.Property<string>("arastirmaci")
                        .HasColumnType("text");

                    b.Property<DateTime>("atamaTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("atananUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("atayanUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("bakanlikOnayvarmi")
                        .HasColumnType("text");

                    b.Property<long>("basvuruId")
                        .HasColumnType("bigint");

                    b.Property<string>("basvuruformvarmi")
                        .HasColumnType("text");

                    b.Property<string>("butceFormvarmi")
                        .HasColumnType("text");

                    b.Property<string>("danisman")
                        .HasColumnType("text");

                    b.Property<string>("dilekceBasvurusuUygunmu")
                        .HasColumnType("text");

                    b.Property<string>("etikkurulvarmi")
                        .HasColumnType("text");

                    b.Property<string>("girisimselUygulama")
                        .HasColumnType("text");

                    b.Property<string>("gorusler")
                        .HasColumnType("text");

                    b.Property<string>("kontrolDurum")
                        .HasColumnType("text");

                    b.Property<DateTime>("kontrolTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("kullanilacakevraklarvarmi")
                        .HasColumnType("text");

                    b.Property<string>("kurum")
                        .HasColumnType("text");

                    b.Property<string>("kurumUstYazi")
                        .HasColumnType("text");

                    b.Property<string>("onizinformvarmi")
                        .HasColumnType("text");

                    b.Property<string>("ozgecmisvarmi")
                        .HasColumnType("text");

                    b.Property<string>("prospektifmi")
                        .HasColumnType("text");

                    b.Property<string>("ucedetLitaratur")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("atananUserId");

                    b.HasIndex("atayanUserId");

                    b.HasIndex("basvuruId");

                    b.ToTable("kontrols");
                });

            modelBuilder.Entity("argebackend.Models.Ozgecmis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ad")
                        .HasColumnType("text");

                    b.Property<string>("arastirmas")
                        .HasColumnType("text");

                    b.Property<string>("deneyims")
                        .HasColumnType("text");

                    b.Property<DateTime>("dogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("dogumYeri")
                        .HasColumnType("text");

                    b.Property<string>("egitims")
                        .HasColumnType("text");

                    b.Property<string>("eposta")
                        .HasColumnType("text");

                    b.Property<bool>("sorumlu")
                        .HasColumnType("boolean");

                    b.Property<string>("soyad")
                        .HasColumnType("text");

                    b.Property<string>("tc")
                        .HasColumnType("text");

                    b.Property<string>("unvans")
                        .HasColumnType("text");

                    b.Property<string>("yabanciDil")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ozgecmisis");
                });

            modelBuilder.Entity("argebackend.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("departmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool?>("isArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<long?>("phone")
                        .HasColumnType("bigint");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("argebackend.Models.Timeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("HVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("durum")
                        .HasColumnType("text");

                    b.Property<string>("not")
                        .HasColumnType("text");

                    b.Property<int>("notType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("userId");

                    b.ToTable("timelines");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("argebackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("argebackend.Models.Basvuru", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("argebackend.Models.Kontrol", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", "atananUser")
                        .WithMany()
                        .HasForeignKey("atananUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("argebackend.Models.ApplicationUser", "atayanUser")
                        .WithMany()
                        .HasForeignKey("atayanUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("argebackend.Models.Basvuru", "basvuru")
                        .WithMany()
                        .HasForeignKey("basvuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("atananUser");

                    b.Navigation("atayanUser");

                    b.Navigation("basvuru");
                });

            modelBuilder.Entity("argebackend.Models.Ozgecmis", b =>
                {
                    b.HasOne("argebackend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("argebackend.Models.Timeline", b =>
                {
                    b.HasOne("argebackend.Models.Basvuru", "basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("argebackend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("basvuru");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
